// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using VoteService.Data.Context;

namespace VoteService.Data.Migrations
{
    [DbContext(typeof(VoteContext))]
    [Migration("20190403202924_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("VoteService.Data.Entities.Vote", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProfileId");

                    b.Property<string>("QuestionId");

                    b.Property<bool>("Score");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "QuestionId", "Score")
                        .IsUnique();

                    b.ToTable("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
